### ISSUE TITLE
Index.html path to browse property is incorrect

### ISSUE THREAD

**Issue by ghost** [neo4j-examples/movies-dotnet-neo4jclient#1]
The index page property "Browse to URL" is set as "~/Home/Views/home/index.html". This throws an error. I set mine to "~/Views/home/index.html" to fix it.

**Comment by jexp** [comment]
Would you mind sending an a PR?

**Comment by cskardon** [comment]
Hi @Bsidey - the only reference in the code to `home/index.html` is in the `HomeController` at [Line 14](https://github.com/neo4j-examples/movies-dotnet-neo4jclient/blob/master/Neo4jDotNetDemo/Controllers/HomeController.cs#L14) but it references `~/Views/home/index.html` not '~/Home/Views/home/index.html`

**Comment by cskardon** [comment]
Closing this as it was fixed in #5
