### ISSUE TITLE
Server Error in '/' Application

### ISSUE THREAD

**Issue by issararab** [neo4j-examples/movies-dotnet-neo4jclient#4]
The resource cannot be found. 
  _Description:_ HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

 _Requested URL:_ /Neo4jDotNetDemo/Views/Home/index.html

_Version Information
![1](https://cloud.githubusercontent.com/assets/17605438/15489587/3b5e589e-2161-11e6-8f22-da27d508cab3.png)
_: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1055.0

**Comment by cskardon** [comment]
You can't access the html file directly as it's not treated as content. 
Access to the page is via just the root (http://localhost:33012/) 
Though there is a bug with going to http://localhost:33012/home/index - which I'll fix now.
