### ISSUE TITLE
C# code sampledoes not use official Neo4j driver and associated classes

### ISSUE THREAD

**Issue by fayyazpoonawala** [neo4j-examples/movies-dotnet-neo4jclient#7]
the movies-dotnet-neo4jclient application does not use the official Neo4j driver nuget package and the classes that the blog and use cases mention.
can the example be modified to show how to best use the official neo4j driver?

**Comment by cskardon** [comment]
This example is specifically for the `Neo4jClient` driver, you want to be looking at: https://github.com/neo4j-examples/movies-dotnet-bolt which uses the official driver!
